version: "3"

services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app/routes:ro
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASS: root_pass
      DATABASE_NAME: tutorials
      DATABASE_PORT: 3306
      DATABASE_CONNECTION: mysql
    links:
      - database
